### ISSUE TITLE
Support more imputation options

### ISSUE THREAD

**Issue by ecsalomon** [dssg/timechop#20]
Currently, all missing values are imputed as 0. This is not ideal. Allow user to configure how such values are imputed.... somehow.

**Comment by ecsalomon** [comment]
Also allow an option for no imputation.

**Comment by ecsalomon** [comment]
Timechop might store "parent" matrix in project folder; imputation to be done elsewhere in pipeline, and then child matrices with imputed values.

**Comment by thcrock** [comment]
Now in https://github.com/dssg/architect/issues/21
