### ISSUE TITLE
Investigate alphabetizing feature columns & feature list

### ISSUE THREAD

**Issue by ecsalomon** [dssg/timechop#36]
Alphabetizing the order of columns and the order of features in the metadata may help to ensure hash ids are shared for matrices with the same feature sets.

This seems relatively trivial within feature tables (sort the list of columns before selection), and that may be sufficient.

**Comment by thcrock** [comment]
At some point since this, the feature list that gets put in was sorted ( https://github.com/dssg/architect/blob/master/architect/utils.py#L83 ) - reopen in Architect if this isn't correct.
